### ISSUE TITLE
"Help Regarding How to deploy the Site"

### ISSUE THREAD

**Issue by skgupta507** [Zeddxx/enimi#1]
Hey @Zeddxx can u help me how to deploy the site on platforms like vercel, Netlify And Render.
i tried doing it as i do for a normal next.js project with the command Yarn start  but that didnt come out sucessfully i got errors.
so can u  please guuide me how to deploy this on my own.

**Comment by Zeddxx** [comment]
@skgupta507 i have used npm and deployed it on render. I haven’t used yarn before while building the Mern application. Try to use npm for now and deploy your instance on render.

**Comment by Zeddxx** [comment]
Follow this:
Build command: `cd client && npm install && npm run build && cd ../server && npm install && npm run build `
Start command: `cd server && npm start`
